### ISSUE TITLE
ssl verification support

### ISSUE THREAD

**Issue by thatsk** [stefan-hudelmaier/docker-registry-to-registry-sync#2]
docker run --rm -it \
>     -v $(pwd)/config.yml:/config.yml \
>     stefanhudelmaier/docker-registry-to-registry-sync
Unable to find image 'stefanhudelmaier/docker-registry-to-registry-sync:latest' locally
latest: Pulling from stefanhudelmaier/docker-registry-to-registry-sync
1160f4abea84: Pull complete
12143a78200d: Pull complete
30e514735382: Pull complete
ee1567a5cc3a: Pull complete
9de4ef89d96d: Pull complete
f8663bf66410: Pull complete
e5a893d57fe2: Pull complete
f779b2b84017: Pull complete
Digest: sha256:d64550f53c3a92999bc6f6dd3b52579c9190c85c1ac441761297c1685dd2b583
Status: Downloaded newer image for stefanhudelmaier/docker-registry-to-registry-sync:latest
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/local/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='sourceregistryserver', port=443): Max retries exceeded with url: /v2/ (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-registry-to-registry-sync.py", line 77, in <module>
    password=src_password)
  File "/usr/local/lib/python3.6/site-packages/docker_registry_client/DockerRegistryClient.py", line 28, in __init__
    api_timeout=api_timeout)
  File "/usr/local/lib/python3.6/site-packages/docker_registry_client/_BaseClient.py", line 292, in BaseClient
    v2_client.check_status()
  File "/usr/local/lib/python3.6/site-packages/docker_registry_client/_BaseClient.py", line 172, in check_status
    return self._http_call('/v2/', get)
  File "/usr/local/lib/python3.6/site-packages/docker_registry_client/_BaseClient.py", line 55, in _http_call
    response = self._http_response(url, method, data=data, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/docker_registry_client/_BaseClient.py", line 265, in _http_response
    data=data, headers=header, **self.method_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='sourceregistryserver', port=443): Max retries exceeded with url: /v2/ (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),))

**Comment by Twistz1z** [comment]
I have the same error with you. Do you have some methods to solve it?
